// Code generated by Wire protocol buffer compiler, do not edit.
// Source: component.RepeatingMessage in RepeatingMessage.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package component

import com.squareup.wire.AnyMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class RepeatingMessage(
  messages: List<AnyMessage> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RepeatingMessage, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.AnyMessage#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val messages: List<AnyMessage> = immutableCopyOf("messages", messages)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RepeatingMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (messages != other.messages) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + messages.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (messages.isNotEmpty()) result += """messages=$messages"""
    return result.joinToString(prefix = "RepeatingMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(messages: List<AnyMessage> = this.messages, unknownFields: ByteString = this.unknownFields): RepeatingMessage = RepeatingMessage(messages, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RepeatingMessage> = object : ProtoAdapter<RepeatingMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      RepeatingMessage::class, 
      "type.googleapis.com/component.RepeatingMessage", 
      PROTO_3, 
      null, 
      "RepeatingMessage.proto"
    ) {
      override fun encodedSize(`value`: RepeatingMessage): Int {
        var size = value.unknownFields.size
        size += AnyMessage.ADAPTER.asRepeated().encodedSizeWithTag(1, value.messages)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RepeatingMessage) {
        AnyMessage.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.messages)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RepeatingMessage) {
        writer.writeBytes(value.unknownFields)
        AnyMessage.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.messages)
      }

      override fun decode(reader: ProtoReader): RepeatingMessage {
        val messages = mutableListOf<AnyMessage>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> messages.add(AnyMessage.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return RepeatingMessage(
          messages = messages,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RepeatingMessage): RepeatingMessage = value.copy(
        messages = value.messages.redactElements(AnyMessage.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
