// Code generated by Wire protocol buffer compiler, do not edit.
// Source: component.TextComponent2 in TextMessage2.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package component

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class TextComponent2(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val text: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TextComponent2, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TextComponent2) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + text.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """text=${sanitize(text)}"""
    return result.joinToString(prefix = "TextComponent2{", separator = ", ", postfix = "}")
  }

  public fun copy(text: String = this.text, unknownFields: ByteString = this.unknownFields): TextComponent2 = TextComponent2(text, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextComponent2> = object : ProtoAdapter<TextComponent2>(
      FieldEncoding.LENGTH_DELIMITED, 
      TextComponent2::class, 
      "type.googleapis.com/component.TextComponent2", 
      PROTO_3, 
      null, 
      "TextMessage2.proto"
    ) {
      override fun encodedSize(`value`: TextComponent2): Int {
        var size = value.unknownFields.size
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.text)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TextComponent2) {
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TextComponent2) {
        writer.writeBytes(value.unknownFields)
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text)
        }
      }

      override fun decode(reader: ProtoReader): TextComponent2 {
        var text: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TextComponent2(
          text = text,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TextComponent2): TextComponent2 = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
